services:
  - type: web
    name: genia-quadras
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main_minimal:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_DB
        value: vaiterplay
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: USE_LLM
        value: "true"
      - key: DEBUG
        value: "false"
      - key: LOG_LEVEL
        value: INFO
